### ISSUE TITLE
Form not secure coming/Page not secure.

### ISSUE THREAD

**Issue by Harsh-Kuber** [Socklet/Main_Website#18]
Form not secure coming and because of that people will not submit and contact us :(
![image](https://user-images.githubusercontent.com/67162865/108805166-66490280-75c5-11eb-8125-4d8b4e10987c.png)

**Comment by Harsh-Kuber** [comment]
@AanshumaanShrijaiphysics I have assigned you this bug

**Comment by AanshumaanShrijaiphysics** [comment]
ok, I'll do it.

**Comment by AanshumaanShrijaiphysics** [comment]
This is a bit complicated

**Comment by Harsh-Kuber** [comment]
I know

**Comment by Harsh-Kuber** [comment]
I searched gogle we need to write **node API**

**Comment by AanshumaanShrijaiphysics** [comment]
We can also use Python Django or java Spring. I prefer Python Django, because node.js is just an extension to javascript and is not widely used (and I've not learned node too :) ) We'll use python django, because the server-side validation is more secure, more correct and more traditional then client-side validation. Are you okay with using Python Django.

**Comment by Harsh-Kuber** [comment]
ok

**Comment by AanshumaanShrijaiphysics** [comment]
👍🏻

**Comment by AanshumaanShrijaiphysics** [comment]
Woah!!! I found something helpful, I was finding what was making it unsecure, but I found out that [mailto:harsh.kuber@outlook.com%20,%20aanshumaanshrijai@gmail.com](mailto:harsh.kuber@outlook.com%20,%20aanshumaanshrijai@gmail.com) url is unsecure, I'll see what's making it unsecure.

![image](https://user-images.githubusercontent.com/71839305/109384723-d84a8000-7914-11eb-9c34-71ecdca70025.png)

**Comment by Harsh-Kuber** [comment]
I also found that, mailto:blablabalbal doesn't have **https**  so  that's making it unsecure I will send one pic see that.
![image](https://user-images.githubusercontent.com/67162865/109392902-c54fa400-7944-11eb-91f8-5db9444b2e7c.png)see it doesn't have https in the start.

**Comment by AanshumaanShrijaiphysics** [comment]
umm... yeah https is the reason but we can't do anything because this is a function that is handled on the client-side and http takes it from the server and https makes it secure. We'll not use JavaScript for that because it's making it unsecure we'll do server-side validation only.

**Comment by Harsh-Kuber** [comment]
I fixed it :)
