### ISSUE TITLE
Need to add manual option in contact us.

### ISSUE THREAD

**Issue by Harsh-Kuber** [Socklet/Main_Website#21]
Need to add manual option in contact us.

In easy words this thing

![](https://user-images.githubusercontent.com/67162865/108985119-adfb8700-76b6-11eb-8f29-a883907d849c.png)

**Comment by AanshumaanShrijaiphysics** [comment]
I didn't understand it, can you describe it broadly

**Comment by Harsh-Kuber** [comment]
In easy words this thing
![image](https://user-images.githubusercontent.com/67162865/108985119-adfb8700-76b6-11eb-8f29-a883907d849c.png)

**Comment by Harsh-Kuber** [comment]
I am adding the bottom part

**Comment by AanshumaanShrijaiphysics** [comment]
oh, okay

**Comment by Harsh-Kuber** [comment]
Done
