### ISSUE TITLE
Change the look and position of Contact Us button

### ISSUE THREAD

**Issue by AanshumaanShrijaiphysics** [Socklet/Main_Website#23]
Currently the contact us button's position looks like this:-

![image](https://user-images.githubusercontent.com/71839305/109126823-b665c780-7773-11eb-8b8e-c659f378f279.png)

The new position of the Contact Us button should be somewhere here:-

![image](https://user-images.githubusercontent.com/71839305/109127153-1ceae580-7774-11eb-827a-d71aa624b7c8.png)

We need to do this to accomplish a Grid Layout of our website.

**Comment by Harsh-Kuber** [comment]
Ok I'll do it.

**Comment by Harsh-Kuber** [comment]
Done.
